#baseURL = "https://gabrielbarros36.github.io/personal/"
baseURL = "https://gabe.build/"
languageCode = "en-us"
title = "Gabriel Romanini de Barros"
pygmentsUseClasses = true
summaryLength = 15

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 1
[menu.main.params]
    style = "text-critical-600"
    style_active = "bg-critical-100 dark:bg-critical-800 dark:bg-opacity-[30%]"

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2
[menu.main.params]
    style = "text-info-600"
    style_active = "bg-info-100 dark:bg-info-800 dark:bg-opacity-[30%]"

# Posts section - uncomment to show posts tab in navigation
# [[menu.main]]
# name = "Posts"
# url = "/posts/"
# weight = 2
# [menu.main.params]
#     style = "text-info-600"
#     style_active = "bg-info-100 dark:bg-info-800 dark:bg-opacity-[30%]"

# [[menu.main]]
# name = "Log"
# url = "/log/"
# weight = 3
# [menu.main.params]
#     style = "text-warning-600"
#     style_active = "bg-warning-100 dark:bg-warning-800 dark:bg-opacity-[30%]"

[[menu.main]]
name = "Reading"
url = "/reading/"
weight = 3
[menu.main.params]
   style = "text-positive-600"
   style_active = "bg-positive-100 dark:bg-positive-800 dark:bg-opacity-[30%]"

# [[menu.main]] 
# name = "Letter"
# url = "/letter/"
# weight = 5
# [menu.main.params]
#    style = "text-positive-600"
#    style_active = "bg-positive-100 dark:bg-positive-800 dark:bg-opacity-[30%]"
